version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5632:5432'
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
